import { CheckIcon, Cross2Icon, MinusIcon, PinTopIcon, PlusIcon, SewingPinFilledIcon } from '@radix-ui/react-icons';
import { Label } from '@radix-ui/react-label';
import * as Separator from '@radix-ui/react-separator'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from 'components/Accordion';
import { AutoComplete } from 'components/AutoComplete'
import { Box } from 'components/Box';
import Button from 'components/Button';
import { Checkbox, CheckboxIndicator } from 'components/Checkbox';
import Datepicker from 'components/DateRangePicker';
import { Center, Horizontal } from 'components/Flex';
import { Input } from 'components/Input';
import { Seperator } from 'components/Seperator';
import { H2, Text } from 'components/Text';
import { ToggleGroup, ToggleGroupItem } from 'components/ToggleGroup';
import Head from 'next/head'
import { useFieldArray, useForm } from 'react-hook-form';
import { styled } from 'stitches.config';



const FlexField = styled('div', {
  display:"flex",
  alignItems:"center",
  width:'25%',
  my:"$1"
})



export default function Home() {




  const { getValues, setValue, control, register } = useForm();
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray({
    control, // control props comes from useForm (optional: if you are using FormContext)
    name: "test", // unique name for your Field Array

  });


  return (
    <Box css={{
      minWidth: '100vw', minHeight: "100vh",

      backgroundColor: `#b8c6db`,
      backgroundImage: `linear-gradient(315deg, #b8c6db 0%, #f5f7fa 74%)`,
    }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box css={{
        display: "block",
        position: "absolute",
        width: 600,
        top: '50%',
        left: '50%',
        background: "rgba(255,255,255, 1)",
        borderRadius: "$5",
        transform: 'translate(-50%, -50%)',
        padding: "$4",
        maxWidth: "90vw",
      }}>
        <H2 css={{ textAlign: "center" }}>Intinerary Planner</H2>

        <br />
        {fields.map((field, index) => {

          return <Box
            css={{ margin: 0, padding: 0 }}
            key={field.id} // important to include key with field's id
          > <Horizontal
            css={{
              justifyContent: "center",
              alignItems: "center"
            }}

          >
              <AutoComplete

                placeholder='select a destination'
                startEnhancer={<SewingPinFilledIcon />}
                load={async ({ signal, cursor, filterText }) => {
                  if (cursor) {
                    cursor = cursor.replace(/^http:\/\//i, "https://");
                  }

                  let res = await fetch(
                    cursor || `https://swapi.dev/api/people/?search=${filterText}`,
                    { signal }
                  );
                  let json = await res.json();

                  return {
                    items: json.results,
                    cursor: json.next
                  };
                }}
                css={{ wdith: "100%", flex: 1, mr: "$2" }}
                onChange={(val) => setValue(`test.${index}.value`, val)}
              />
              <Button variant='gray' onClick={() => remove(index)}><Cross2Icon /></Button>
            </Horizontal>
            <Center>
              <Box css={{ height: "$5", width: "1px", backgroundColor: "$mauve6" }} />
            </Center>
          </Box>
        })}
        <br />

        <Center>

          <Button
            css={{
              fontWeight: 500
            }}
            variant='white'
            endEnhancer={<PlusIcon />}
            onClick={() => {
              append('', {

              })
            }}>Add destination</Button>
        </Center>


        {/* <button onClick={() => {
          console.log(getValues())
        }}>Submit</button> */}
        <br />
        <Box css={{ mb: "$1", fontWeight: "500" }}>Date range</Box>
        <Datepicker css={{ width: "100%" }}></Datepicker>
        <br />
        <Horizontal>
          <Input css={{ mx: "$1" }} label='Adults' name='adults' type='number' min={0} {...register('adults', { value: 0 })} ></Input>
          <Input css={{ mx: "$1" }} label='Teens' name='teens' type='number' min={0} {...register('teens', { value: 0 })}></Input>
          <Input css={{ mx: "$1" }} label='Kids' name='kids' type='number' min={0} {...register('kids', { value: 0 })}></Input>
        </Horizontal>
        <br />

        <Accordion type="single" defaultValue="item-1" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger>Activities preferences? (optional)</AccordionTrigger>
            <AccordionContent>
              <ToggleGroup css={{ width: "100%", display: "flex" }} type="single" defaultValue="center" aria-label="Text alignment">
                <ToggleGroupItem css={{ flex: 1 }} value="left" aria-label="Left aligned">
                  Popular
                </ToggleGroupItem>
                <ToggleGroupItem css={{ flex: 1 }} value="center" aria-label="Center aligned">
                  Balanced
                </ToggleGroupItem>
                <ToggleGroupItem css={{ flex: 1 }} value="right" aria-label="Right aligned">
                  Hidden gems
                </ToggleGroupItem>
              </ToggleGroup>
              <br />
              <ToggleGroup css={{ width: "100%", display: "flex" }} type="single" defaultValue="center" aria-label="Text alignment">
                <ToggleGroupItem css={{ flex: 1 }} value="left" aria-label="Left aligned">
                  Slow
                </ToggleGroupItem>
                <ToggleGroupItem css={{ flex: 1 }} value="center" aria-label="Center aligned">
                  Middle
                </ToggleGroupItem>
                <ToggleGroupItem css={{ flex: 1 }} value="right" aria-label="Right aligned">
                  Fast-paced
                </ToggleGroupItem>
              </ToggleGroup>
              <br />

              <Horizontal css={{position:"relative", justifyContent:"space-between", alignItems:"center",  flexWrap:"wrap"}}>
                <FlexField>
                  <Checkbox defaultChecked id="c1">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c1">
                    Culture
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c2">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c2">
                    Outdoor
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c3">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c3">
                    Relaxing
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c4">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c4">
                    Romatic
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c5">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c5">
                    Beaches
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c6">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c6">
                    Beaches
                  </Label>
                </FlexField>
               
                

                <FlexField>
                  <Checkbox defaultChecked id="c9">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c9">
                    Shopping
                  </Label>
                </FlexField>
                <FlexField>
                  <Checkbox defaultChecked id="c8">
                    <CheckboxIndicator>
                      <CheckIcon />

                    </CheckboxIndicator>
                  </Checkbox>
                  <Label css={{ paddingLeft: 15 }} htmlFor="c8">
                    Wildlife
                  </Label>
                </FlexField>
              </Horizontal>

            </AccordionContent>
          </AccordionItem>

        </Accordion>
        <br />


        <Button size='lg' css={{ width: "100%" }}>Create Your Trip</Button>
      </Box>
    </Box>
  );
}

